### ISSUE TITLE
can't find some module

### ISSUE THREAD

**Issue by fIappy** [jtpereyda/boofuzz-ftp#2]
Hello, there are some py module can't be found:
```
from boofuzz.utils.debugger_thread_simple import DebuggerThreadSimple
from boofuzz.utils.process_monitor_local import ProcessMonitorLocal
```

**Comment by jtpereyda** [comment]
@fIappy Thanks! This is code from the [local-procmon branch](https://github.com/jtpereyda/boofuzz/tree/local-procmon) in boofuzz. Should be merged this week.

In retrospect I should have put these changes on a branch too. My bad.

**Comment by jtpereyda** [comment]
@fIappy that branch is merged now, so this code should work if you pull the latest boofuzz code. It's not yet in a Pypi release.

I'll be more careful in the future. Thanks for filing the issue, and happy fuzzing!
